apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  labels:
    {{- include "labels.common" $ | nindent 4 }}
  name: {{ $.Values.clusterID }}-karpenter
  namespace: {{ $.Release.Namespace }}
spec:
  catalog: giantswarm-test
  config:
    configMap:
      name: {{ $.Values.clusterID }}-cluster-values
      namespace: {{ $.Release.Namespace }}
  install:
    timeout: "10m"
  upgrade: 
    timeout: "10m"
  kubeConfig:
    context:
      name: {{ $.Values.clusterID }}-admin@{{ $.Values.clusterID }}
    inCluster: false
    secret:
      name: {{ $.Values.clusterID }}-kubeconfig
      namespace: {{ $.Release.Namespace}}
  name: karpenter
  namespace: kube-system
  version: 0.14.0-f7bf2055ade21a70009ff9cde304751b20753f26
  extraConfigs:
  - kind: configMap
    name: {{ $.Values.clusterID }}-crossplane-config
    namespace: {{ $.Release.Namespace }}
{{- if (($.Values.karpenter).values) }}
  - kind: configMap
    name: {{ $.Values.clusterID }}-karpenter-config
    namespace: {{ $.Release.Namespace }}
{{- end }}
---
apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  labels:
    {{- include "labels.common" $ | nindent 4 }}
  annotations:
    app-operator.giantswarm.io/depends-on: {{ $.Values.clusterID }}-karpenter
  name: {{ $.Values.clusterID }}-karpenter-nodepools
  namespace: {{ $.Release.Namespace }}
spec:
  catalog: giantswarm-test
  config:
    configMap:
      name: {{ $.Values.clusterID }}-cluster-values
      namespace: {{ $.Release.Namespace }}
  install:
    timeout: "10m"
  upgrade: 
    timeout: "10m"
  kubeConfig:
    context:
      name: {{ $.Values.clusterID }}-admin@{{ $.Values.clusterID }}
    inCluster: false
    secret:
      name: {{ $.Values.clusterID }}-kubeconfig
      namespace: {{ $.Release.Namespace}}
  name: karpenter-nodepools
  namespace: kube-system
  version: 0.0.0-7ad48a5c6a875f04c6762600af55f18458d58615
  extraConfigs:
  - kind: configMap
    name: {{ $.Values.clusterID }}-karpenter-nodepools-config
    namespace: {{ $.Release.Namespace }}
---
apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  labels:
    {{- include "labels.common" $ | nindent 4 }}
  name: {{ $.Values.clusterID }}-capa-karpenter-taint-remover
  namespace: {{ $.Release.Namespace }}
spec:
  catalog: giantswarm-test
  config:
    configMap:
      name: {{ $.Values.clusterID }}-cluster-values
      namespace: {{ $.Release.Namespace }}
  install:
    timeout: "10m"
  upgrade:
    timeout: "10m"
  kubeConfig:
    context:
      name: {{ $.Values.clusterID }}-admin@{{ $.Values.clusterID }}
    inCluster: false
    secret:
      name: {{ $.Values.clusterID }}-kubeconfig
      namespace: {{ $.Release.Namespace}}
  name: capa-karpenter-taint-remover
  namespace: kube-system
  version: 0.4.0-49140da831687d50be5b61ba69ca4a14a80b8629
---
apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  labels:
    app-operator.giantswarm.io/version: 0.0.0
    {{- include "labels.common" $ | nindent 4 }}
  name: {{ $.Values.clusterID }}-karpenter-crossplane-resources
  namespace: {{ $.Release.Namespace }}
spec:
  catalog: giantswarm
  install:
    timeout: "10m"
  upgrade:
    timeout: "10m"
  kubeConfig:
    inCluster: true
  name: karpenter-crossplane-resources
  namespace: {{ $.Release.Namespace }}
  version: 0.1.1
  extraConfigs:
  - kind: configMap
    name: {{ $.Values.clusterID }}-crossplane-config
    namespace: {{ $.Release.Namespace }}
