apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  labels:
    {{- include "labels.common" $ | nindent 4 }}
  annotations:
    app-operator.giantswarm.io/depends-on: {{ include "resource.default.name" $ }}-karpenter-crossplane-resources
  name: {{ $.Values.clusterID }}-karpenter
  namespace: {{ $.Release.Namespace }}
spec:
  catalog: giantswarm-test
  config:
    configMap:
      name: {{ $.Values.clusterID }}-cluster-values
      namespace: {{ $.Release.Namespace }}
  install:
    timeout: "10m"
  upgrade: 
    timeout: "10m"
  kubeConfig:
    context:
      name: {{ $.Values.clusterID }}-admin@{{ $.Values.clusterID }}
    inCluster: false
    secret:
      name: {{ $.Values.clusterID }}-kubeconfig
      namespace: {{ $.Release.Namespace}}
  name: karpenter
  namespace: kube-system
  version: 0.14.0-8d4ce56aab695e5037f4499cd9b07060e7a60f8d
  extraConfigs:
  - kind: configMap
    name: {{ $.Values.clusterID }}-crossplane-config
    namespace: {{ $.Release.Namespace }}
{{- if (($.Values.karpenter).values) }}
  - kind: configMap
    name: {{ $.Values.clusterID }}-karpenter-config
    namespace: {{ $.Release.Namespace }}
{{- end }}
---
apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  labels:
    {{- include "labels.common" $ | nindent 4 }}
  name: {{ $.Values.clusterID }}-capa-karpenter-taint-remover
  namespace: {{ $.Release.Namespace }}
spec:
  catalog: giantswarm
  config:
    configMap:
      name: {{ $.Values.clusterID }}-cluster-values
      namespace: {{ $.Release.Namespace }}
  install:
    timeout: "10m"
  upgrade:
    timeout: "10m"
  kubeConfig:
    context:
      name: {{ $.Values.clusterID }}-admin@{{ $.Values.clusterID }}
    inCluster: false
    secret:
      name: {{ $.Values.clusterID }}-kubeconfig
      namespace: {{ $.Release.Namespace}}
  name: capa-karpenter-taint-remover
  namespace: kube-system
  version: 0.6.0
---
apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  labels:
    app-operator.giantswarm.io/version: 0.0.0
    {{- include "labels.common" $ | nindent 4 }}
  name: {{ $.Values.clusterID }}-karpenter-crossplane-resources
  namespace: {{ $.Release.Namespace }}
spec:
  catalog: giantswarm
  install:
    timeout: "10m"
  upgrade:
    timeout: "10m"
  kubeConfig:
    inCluster: true
  name: karpenter-crossplane-resources
  namespace: {{ $.Release.Namespace }}
  version: 0.1.3
  extraConfigs:
  - kind: configMap
    name: {{ $.Values.clusterID }}-crossplane-config
    namespace: {{ $.Release.Namespace }}
