{{- if (($.Values.karpenter).values) }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "labels.common" $ | nindent 4 }}
  name: {{ $.Values.clusterID }}-karpenter-config
  namespace: {{ $.Release.Namespace }}
data:
  values: |
  {{- (tpl ($.Values.karpenter.values | toYaml | toString) $) | nindent 4 }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "labels.common" $ | nindent 4 }}
  name: {{ $.Values.clusterID }}-karpenter-nodepools-config
  namespace: {{ $.Release.Namespace }}
data:
  values: |
  {{- (tpl ($.Values.karpenterNodepools.values | toYaml | toString) $) | nindent 4 }}
