---
apiVersion: v1
data:
  values: |
    global:
      connectivity:
        availabilityZoneUsageLimit: 3
        network: {}
        topology: {}
      controlPlane: {}
      metadata:
        name: karpexample
        organization: giantswarm
      nodePools:
        nodepool0:
          instanceType: m5.large
          maxSize: 1
          minSize: 1
          rootVolumeSizeGB: 300
      providerSpecific: {}
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    giantswarm.io/cluster: karpexample
  name: karpexample-userconfig
  namespace: org-giantswarm
---
apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  labels:
    app-operator.giantswarm.io/version: 0.0.0
  name: karpexample
  namespace: org-giantswarm
spec:
  catalog: cluster
  config:
    configMap:
      name: ""
      namespace: ""
    secret:
      name: ""
      namespace: ""
  kubeConfig:
    context:
      name: ""
    inCluster: true
    secret:
      name: ""
      namespace: ""
  name: cluster-aws
  namespace: org-giantswarm
  userConfig:
    configMap:
      name: karpexample-userconfig
      namespace: org-giantswarm
  version: 0.72.0
---
apiVersion: v1
data:
  values: |
    clusterName: karpexample
    organization: giantswarm
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    giantswarm.io/cluster: karpexample
  name: karpexample-default-apps-userconfig
  namespace: org-giantswarm
---
apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  labels:
    app-operator.giantswarm.io/version: 0.0.0
    giantswarm.io/cluster: karpexample
    giantswarm.io/managed-by: cluster
  name: karpexample-default-apps
  namespace: org-giantswarm
spec:
  catalog: cluster
  config:
    configMap:
      name: karpexample-cluster-values
      namespace: org-giantswarm
    secret:
      name: ""
      namespace: ""
  kubeConfig:
    context:
      name: ""
    inCluster: true
    secret:
      name: ""
      namespace: ""
  name: default-apps-aws
  namespace: org-giantswarm
  userConfig:
    configMap:
      name: karpexample-default-apps-userconfig
      namespace: org-giantswarm
  version: 0.51.0
---
apiVersion: v1
data:
  values: |
    karpenter:
      values:
        defaultProvisioner:
          enabled: true
          nodePoolName: nodepool0
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    giantswarm.io/cluster: karpexample
  name: karpexample-karpenter-bundle-user-values
  namespace: org-giantswarm
---
apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  labels:
    app-operator.giantswarm.io/version: 0.0.0
    app.kubernetes.io/name: karpenter-bundle
    giantswarm.io/cluster: karpexample
  name: karpexample-karpenter-bundle
  namespace: org-giantswarm
spec:
  catalog: giantswarm
  config:
    configMap:
      name: karpexample-cluster-values
      namespace: org-giantswarm
    secret:
      name: ""
      namespace: ""
  kubeConfig:
    context:
      name: karpexample
    inCluster: true
    secret:
      name: karpexample-kubeconfig
      namespace: org-giantswarm
  name: karpenter-bundle
  namespace: org-giantswarm
  userConfig:
    configMap:
      name: karpexample-karpenter-bundle-user-values
      namespace: org-giantswarm 
  version: 1.0.0
