apiVersion: v2
name: karpenter-bundle
description: Karpenter Bundle with crossplane resources
home: https://github.com/giantswarm/karpenter-bundle
version: 0.1.1
annotations:
  application.giantswarm.io/team: phoenix
  application.giantswarm.io/in-cluster-app: "true"
  application.giantswarm.io/app-type: "bundle"
